#bellsoft/liberica-openjdk-debian:23
#bellsoft/liberica-openjdk-alpine-musl:23 optimized but need a font
#bellsoft/liberica-runtime-container:jre-23-musl optimized but need a font
services:
  liberica-runtime-8:
    build:
      context: . # Build context is the current directory
      dockerfile: Dockerfiles/Dockerfile8 # Name of the dockerfile
    image: liberica-runtime-8 # Sets the image name after build
  liberica-runtime-11:
    build:
      context: . # Build context is the current directory
      dockerfile: Dockerfiles/Dockerfile11 # Name of the dockerfile
    image: liberica-runtime-11 # Sets the image name after build
  liberica-runtime-17:
    build:
      context: . # Build context is the current directory
      dockerfile: Dockerfiles/Dockerfile17 # Name of the dockerfile
    image: liberica-runtime-17 # Sets the image name after build
  liberica-runtime-21:
    build:
      context: . # Build context is the current directory
      dockerfile: Dockerfiles/Dockerfile21 # Name of the dockerfile
    image: liberica-runtime-21 # Sets the image name after build
  liberica-runtime-21-glibc:
    build:
      context: . # Build context is the current directory
      dockerfile: Dockerfiles/Dockerfile21-glibc # Name of the dockerfile
    image: liberica-runtime-21-glibc # Sets the image name after build
  liberica-runtime-21-nikmusl:
    build:
      context: . # Build context is the current directory
      dockerfile: Dockerfiles/Dockerfile21-nikmusl # Name of the dockerfile
    image: liberica-runtime-21-nikmusl # Sets the image name after build
  liberica-runtime-23:
    build:
      context: . # Build context is the current directory
      dockerfile: Dockerfiles/Dockerfile23 # Name of the dockerfile
    image: liberica-runtime-23 # Sets the image name after build
  liberica-runtime-24:
    build:
      context: . # Build context is the current directory
      dockerfile: Dockerfiles/Dockerfile24 # Name of the dockerfile
    image: liberica-runtime-24 # Sets the image name after build
  liberica-runtime-24-nikmusl:
    build:
      context: . # Build context is the current directory
      dockerfile: Dockerfiles/Dockerfile24-nikmusl # Name of the dockerfile
    image: liberica-runtime-24-nikmusl # Sets the image name after build