name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Java 8, 11, 17: only musl builds
          - java_version: 8
            libc_type: musl
          - java_version: 11
            libc_type: musl
          - java_version: 17
            libc_type: musl
          # Java 21: glibc, musl, nikmusl, and nikglibc builds
          - java_version: 21
            libc_type: glibc
          - java_version: 21
            libc_type: musl
          - java_version: 21
            libc_type: nikmusl
          # Java 23: musl, nikmusl builds
          - java_version: 23
            libc_type: musl

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Dockerfile and Tag
        id: docker_vars
        run: |
          case "${{ matrix.libc_type }}" in
            glibc)
              echo "dockerfile=Dockerfiles/Dockerfile${{ matrix.java_version }}-glibc" >> $GITHUB_OUTPUT
              echo "tag=${{ matrix.java_version }}-glibc" >> $GITHUB_OUTPUT
              ;;
            musl)
              echo "dockerfile=Dockerfiles/Dockerfile${{ matrix.java_version }}" >> $GITHUB_OUTPUT
              echo "tag=${{ matrix.java_version }}-musl" >> $GITHUB_OUTPUT
              ;;
            nikmusl)
              echo "dockerfile=Dockerfiles/Dockerfile${{ matrix.java_version }}-nikmusl" >> $GITHUB_OUTPUT
              echo "tag=${{ matrix.java_version }}-nikmusl" >> $GITHUB_OUTPUT
              ;;
            nikglibc)
              echo "dockerfile=Dockerfiles/Dockerfile${{ matrix.java_version }}-nikglibc" >> $GITHUB_OUTPUT
              echo "tag=${{ matrix.java_version }}-nikglibc" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ steps.docker_vars.outputs.dockerfile }}
          push: true
          tags: rafalohaki/liberica-minecraft:${{ steps.docker_vars.outputs.tag }}
