name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [8, 11, 17, 23 ] # List of Java versions (without 21)
        libc_type: [ musl ]            # Only build musl for these versions
        include:
          - java_version: 21            # Add Java 21 with both libc types
            libc_type: glibc
          - java_version: 21
            libc_type: musl


    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Dockerfile and Tag
        id: docker_vars
        run: |
          if [[ "${{ matrix.libc_type }}" == "glibc" ]]; then
            echo "dockerfile=Dockerfiles/Dockerfile${{ matrix.java_version }}-glibc" >> $GITHUB_OUTPUT
            echo "tag=${{ matrix.java_version }}-glibc" >> $GITHUB_OUTPUT
          else
            echo "dockerfile=Dockerfiles/Dockerfile${{ matrix.java_version }}" >> $GITHUB_OUTPUT
            echo "tag=${{ matrix.java_version }}-musl" >> $GITHUB_OUTPUT
          fi

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ steps.docker_vars.outputs.dockerfile }}
          push: true
          tags: rafalohaki/liberica-minecraft:${{ steps.docker_vars.outputs.tag }}
